packages:
  - packages/*
  - packages/fetch-router/demos/*
  - packages/form-data-parser/demos/*
  - packages/multipart-parser/bench
  - packages/multipart-parser/demos/*
  - packages/node-fetch-server/bench
  - packages/node-fetch-server/demos/*
  - packages/tar-parser/bench
  - scripts
